# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = 1
  end
  
  config.vm.define "external" do |external|
    external.vm.hostname = "external"
    external.vm.network "private_network", ip: "192.168.56.100"
  end  

  config.vm.define "devops" do |cni|
    cni.vm.hostname = "devops"
    cni.vm.network "private_network", ip: "192.168.56.200"
    cni.vm.provision "shell", inline: <<-SHELL
      iptables -P FORWARD ACCEPT
      apt-get update
      apt-get install \
        ca-certificates \
        curl \
        gnupg \
        iproute2 \
        net-tools \
        lsb-release -y
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      echo \
      "deb [arch=$(dpkg --print-architecture) \
      signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] \
      https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      apt-get update
      apt-get install -y docker-ce \
        docker-ce-cli \
        containerd.io \
        docker-compose-plugin \
        jq
      usermod -a -G docker vagrant
    SHELL
  end

end
