# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y net-tools jq cgroup-tools
    echo 1 > /proc/sys/net/ipv4/ip_forward
  SHELL
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = 1
  end
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false

  config.vm.define "devops" do |devops|
    devops.vm.hostname = "devops"
  end
end
