CFSSL_VERSION="1.6.1"
CRICTR_VERSION="1.21.0"
RUNC_VERSION="1.1.1"
CNI_PLUGINS_VERSION="1.1.1"
CONTAINERD_VERSION="1.6.3"
KUBERNETES_VERSION="1.23.5"
HELM_VERSION="3.8.2"

MACHINE_ARCH=$(uname -m)
OS=$(uname -s | tr '[:upper:]' '[:lower:]' )
BINARY_ARACH=${MACHINE_ARCH}

if [[ $MACHINE_ARCH == "x86_64" ]]
then
  BINARY_ARACH="amd64"
fi

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ADDON_DIR="${SCRIPT_DIR}/../add-ons"
BASE_DIR="${SCRIPT_DIR}/../artifacts"
CERT_DIR="${BASE_DIR}/certs"
CONFIG_DIR="${BASE_DIR}/cfg"
DOWNLOAD_DIR="${BASE_DIR}/files"
ADMIN_KUBECONFIG=${CONFIG_DIR}/admin.kubeconfig

SERVICE_IP_RANGE="10.32.0.0/24"
POD_IP_RANGE="10.200.0.0/16"
CLUSTER_DNS_IP="10.32.0.10"
NETWORK="192.168.56."
CONTROLLER_IP_START=10
WORKER_IP_START=50

KUBERNETES_PUBLIC_ADDRESS="192.168.56.11" # controller-1
CONTROLLER_INTERNAL_IP="192.168.56.11"

ETCD_VERSION="3.5.4"
ETCD_SERVERS="https://192.168.56.11:2379"
ETCD_INTERNAL_IP=${CONTROLLER_INTERNAL_IP}

WORKER_PREFIX="worker-"
NUM_CONTROLLER_NODES=1
NUM_WORKER_NODES=2
KUBERNETES_CLUSTER_NAME="kubernetes-the-hard-way"